[project]
name = "blog"
version = "0.1.0"
description = "Mostly lies and rants in plain text"
authors = [{ name = "Hernan Lozano", email = "hernantz@gmail.com" }]
requires-python = ">=3.11,<4"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "pelican>=4.6.0,<5",
    "pelican-sitemap>=1.0.2,<2",
    "csvkit>=1.0.5,<2",
    "Markdown>=3.3.4,<4",
]

[dependency-groups]
dev = []
